### PR TITLE
Fix lines for MASM symbols

### LINKED ISSUE #61: LineProgram::lines_at_offset is pretty slow
Looking at https://github.com/willglynn/pdb/blob/master/src/modi/c13.rs#L897 it seems that getting all the line info for all the files is quadratic in the number of files.

### LINKED ISSUE #63: Cannot retrieve existing lines with lines_at_offset
In inspecting a basic PDB (almost a basic helloworld program compiled with clang on windows), there is a proc symbol for _security_check_cookie (the code should be almost this one: https://github.com/adityaramesh/concurrency_runtime/blob/master/VS2013_SP2/crt/src/AMD64/amdsecgs.asm).
The InternalSectionOffset is {s: 0x1, o: 0x8990} but when I try to get line info I got nothing.
The reason is that the InternalSectionOffset for lines is at {s: 0x1, o: 0x8980}.
My hypothesis is that the executable code is really at 0x8990 (line 47) and there are metadata or padding or whatever at 0x8980.
For info, the code_size of the proc is 33 where it appears to be 49 (33 + 16) in DbgLineSub.
So, I'd say that we shouldn't get "lines_section.header.offset == offset" but take the max before offset.
If you need to have the pdb, then I can share it with you.

### PR DESCRIPTION
**Pull request by jan-auer**
`ProcedureSymbol` records for MASM functions have code ranges associated that do not match the actual code or line records. 

`lines_at_offset` assumed that if there is a lines subsection for a symbol, it shares the exact same start offset as the symbol. However, this is not the case for MASM functions, where the symbol's offset can lie *after* the actual start of the instructions / line records. Since the name of `lines_at_offset` was chosen badly, it is now renamed to `lines_for_symbol`, and explicitly states that it may return line records **outside** of the symbol's stated code range.

A consumer of this should probably collect the line records for each symbol and infer a proper code range.

Also, the internal implementation of `lines_at_offset` was slow in two regards: It had linear runtime complexity, and repeatedly had to iterate through large chunks of memory to find the appropriate section. `LineProgram` now collects and sorts all line sections ahead of time to perform faster binary search.

Fixes #61 
Fixes #63

### CODE REVIEW

**Comment by calixteman** [comment]
Have a look on this file: https://github.com/mozilla/dump_syms/blob/master/test_data/basic-opt32.pdb, in particular for proc symbols located in d:\agent\_work\3\s\src\vctools\crt\vcruntime\src\eh\i386\exsup4.asm.
There are: _local_unwind4, _unwind_handler4, _seh_longjmp_unwind4, _EH4_CallFilterFunc, _EH4_TransferToHandler, _EH4_GlobalUnwind2, _EH4_LocalUnwind:
```bash
[calixte@rouxpanda] ~/dev/mozilla/pdb$ cargo run --release --example pdb_lines ../dump_syms.calixteman/test_data/basic-opt32.pdb | rg '_local_unwind4|_unwind_handler4|_seh_longjmp_unwind4|_EH4_CallFilterFunc|_EH4_TransferToHandler| _EH4_GlobalUnwind2|_EH4_LocalUnwind' -A1
    Finished release [optimized] target(s) in 0.05s
     Running `target/release/examples/pdb_lines ../dump_syms.calixteman/test_data/basic-opt32.pdb`
+ @_EH4_CallFilterFunc@8
  0xaeb0 d:\agent\_work\3\s\src\vctools\crt\vcruntime\src\eh\i386\exsup4.asm:159::Some(0)
--
+ _local_unwind4
  0xaeb0 d:\agent\_work\3\s\src\vctools\crt\vcruntime\src\eh\i386\exsup4.asm:159::Some(0)
--
+ _seh_longjmp_unwind4
  0xaeb0 d:\agent\_work\3\s\src\vctools\crt\vcruntime\src\eh\i386\exsup4.asm:159::Some(0)
--
- _unwind_handler4
  0xaeb0 d:\agent\_work\3\s\src\vctools\crt\vcruntime\src\eh\i386\exsup4.asm:159::Some(0)
--
+ @_EH4_LocalUnwind@16
  0xaeb0 d:\agent\_work\3\s\src\vctools\crt\vcruntime\src\eh\i386\exsup4.asm:159::Some(0)
--
+ @_EH4_TransferToHandler@8
  0xaeb0 d:\agent\_work\3\s\src\vctools\crt\vcruntime\src\eh\i386\exsup4.asm:159::Some(0)
```

The lines for each symbol start at 0xaeb0 which is wrong.
So I think that the correct way to get the lines is to get the corresponding section and then get the line with the the correct offset to match the offset given in parameter.
But when getting lines iterator starting at correct line for _local_unwind4, we'll get some extra lines corresponding to _seh_longjmp_unwind4.
So I think lines_symbol should have a length parameter (which would be symbol length) to return an iterator on the lines where line offset is between given offset and given offset+length to be sure to get lines for the symbol.
But that means that line.length computation for the last line should be done with symbol length (and not next line address).

**Comment by calixteman** [comment]
FYI, all the function findLines** from DIA sdk have a length argument:
https://docs.microsoft.com/en-us/visualstudio/debugger/debug-interface-access/idiasession-findlinesbyaddr?view=vs-2019
So I think it makes really sense to have the same here.

**Comment by jan-auer** [comment]
That's a good point. I was sort of assuming that the user of `lines_at_offset` might want to check manually, since it's quite easy to stop iterating. But with `lines_for_symbol` it makes much more sense to pass in the length as well.

Alright, let's update the tests to use the above functions and then see if we can get correct behavior. For reference, do you have the **expected** lines for the functions you pasted above? 

Also, what if the given offset points into the middle of a line record? Do you expect the line record to be included or not? (i.e. is the first line _covering_ the given offset or _at or after_ the given offset)?

File: src/modi/mod.rs [hunk 1]
```diff
@@ -169,6 +169,20 @@ pub struct LineInfo {
...
 }
 
+impl LineInfo {
+    pub(crate) fn set_end(&mut self, end_offset: PdbInternalSectionOffset) {
+        debug_assert!(self.offset.section == end_offset.section);
+        if self.offset.section != end_offset.section {
+            return;
+        }
+
+        let length = end_offset.offset - self.offset.offset;
```
Comment (calixteman) [inline src/modi/mod.rs]: I get a "subtract with overflow" when iterating on line_program.lines() for this pdb:
https://github.com/mozilla/dump_syms/blob/master/test_data/dump_syms_regtest64.pdb
and this module:
Module { info: DBIModuleInfo { opened: 0, section: DBISectionContribution { section: 1, _padding1: 0, offset: 38556, size: 32, characteristics: 1613770784, module: 27, _padding2: 0, data_crc: 3266334926, reloc_crc: 0 }, flags: 0, stream: StreamIndex(39), symbols_size: 452, lines_size: 0, c13_lines_size: 2304, files: 91, _padding: 0, filename_offsets: 34310784, source: 0, compiler: 0 }, module_name: RawString("f:\\binaries\\Intermediate\\vctools\\crt_bld\\SELF_64_amd64\\crt\\prebuild\\build\\amd64\\mt_obj\\nativec\\\\initcon.obj"), object_file_name: RawString("C:\\Program Files (x86)\\Microsoft Visual Studio 12.0\\VC\\LIB\\amd64\\LIBCMT.lib") }

**Comment by calixteman** [comment]
Yep the output for security_check_cookie is correct.
For the above functions: I get lines but as explained I get more lines than expected.
About offset in the middle of line record: I'd say it shouldn't happen but who knows...
So maybe return an Err in this case and let the user decides what to do in using lines for example or maybe something is wrong in the pdb...

File: src/modi/c13.rs [hunk 2]
```diff
@@ -637,19 +652,49 @@ impl<'a> FallibleIterator for C13LineIterator<'a> {
...
+            columns: DebugColumnsIterator::default(),
+            last_info: None,
+        }
+    }
+}
+
+impl fmt::Debug for C13LineIterator<'_> {
+    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
+        f.debug_struct("LineIterator")
+            .field("sections", &self.sections.as_slice())
```
Comment (willglynn) [inline src/modi/c13.rs]: 👍

**Comment by jan-auer** [comment]
This is still work in progress, unfortunately. I will have to rebase this on latest `master`, and then revisit the behavior based on:

> For the above functions: I get lines but as explained I get more lines than expected.

File: src/modi/c13.rs [hunk 3]
```diff
@@ -864,53 +909,85 @@ impl<'a> FallibleIterator for C13FileIterator<'a> {
...
+            match sec.kind {
+                DebugSubsectionKind::FileChecksums => {
+                    file_checksums = DebugFileChecksumsSubsection::parse(sec.data)?;
+                }
+                DebugSubsectionKind::Lines => {
+                    let lines_section = DebugLinesSubsection::parse(sec.data)?;
+                    if let Some(last_offset) = last_offset {
+                        sections_sorted &= lines_section.header.offset < last_offset;
+                    }
+                    last_offset = Some(lines_section.header.offset);
```
Comment (Swatinem) [inline src/modi/c13.rs:935]: This should probably use `lines_key`, as only considering `offset` is not enough for our compound sort key.
Also, not sure this is worth optimizing for anyway, as `sort_unstable_by_key` only does a linear `O(n)` scan anyways if things *are* sorted.

File: src/modi/mod.rs (hunk 1 above)
Comment (Swatinem) [reply src/modi/mod.rs:179]: I wonder if this happens due to wrong sorting due to `sections_sorted` as I pointed out above. If the sort order is correct, the only other place where the `end_offset` could potentially be wrong would be:

```
last_line.set_end(section_header.offset + section_header.code_size);
```

for the very last entry.

**Review by Swatinem — COMMENTED** [review]
I think @calixteman did point to a potential problem that should still be investigated. Is it possible to fuzz this somehow?

File: src/modi/mod.rs (hunk 1 above)
Comment (jan-auer) [reply src/modi/mod.rs:204]: You're correct, it was the sort order because I was sorting by offset rather than section + offset. Reproduced with the above PDB and fixed through always sorting the sections. I'll still guard against this.

File: src/modi/c13.rs (hunk 3 above)
Comment (jan-auer) [reply src/modi/c13.rs]: Great catch, thank you. I went with your recommendation and sort always now.
